// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HelpLayout: typeof import('./src/components/helpLayout/HelpLayout.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    UserLayout: typeof import('./src/components/userLayout/UserLayout.vue')['default']
  }
}

export { }
